project:
  type: website
  render:
    - "*.qmd"
    - "!LICENSE.md"
    - "!README.md"

website:
  title: "Data for Decision Makers"
  site-url: https://d4dm.org
  navbar:
    title: false
    #background: success
    logo: images/d4dm.png
    logo-alt: d4dm
    tools:
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/company/d4dm
      - icon: mastodon
        aria-label: Mastodon
        href: https://mastodon.social/@d4dm
        rel: me
      - icon: github
        aria-label: GitHub
        href: https://github.com/data4decisionmakers
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about/index.qmd
      - text: Blog
        href: blog.qmd
      - text: Capacity Building
        menu:
          - href: capacity.qmd
          - text: Data Literacy Series
            href: courses/data-literacy-short-course.qmd
          - text: Courses
            href: courses/index.qmd
      # - text: Resources
      #   href: resources/index.qmd
      - text: Community
        href: community/index.qmd
  open-graph:
    site-name: d4dm
  page-footer:
    center: "Copyright 2026, D4DM"
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/data4decisionmakers/data4decisionmakers.github.io
  repo-actions: [edit, issue]
  issue-url: https://github.com/data4decisionmakers/data4decisionmakers.github.io/issues
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: G-N5RC41JEQ8
    anonymize-ip: true

format:
  html:
    theme: [pulse, custom.scss]
    css: style.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    toc: false