project:
  type: website

website:
  title: ""
  site-url: https://d4dm.org
  navbar:
    title: ""
    #background: success
    logo: images/d4dm.png
    logo-alt: d4dm
    tools:
      - icon: mastodon
        aria-label: Mastodon
        href: https://mastodon.social/@d4dm
        rel: me
      - icon: github
        aria-label: GitHub
        href: https://github.com/data4decisionmakers
    left:
      - href: index.qmd
        text: Home
      # - text: Packages
      #   href: packages/index.qmd
      # - text: About
      #   menu:
      #     - href: about/team.qmd
      #     - href: about/contact.qmd
  open-graph:
    site-name: d4dm
  page-footer:
    center: "Copyright 2025, D4DM"
    background: light
    border: false
  reader-mode: true
  repo-url: https://github.com/data4decisionmakers/data4decisionmakers.github.io
  repo-actions: [edit, issue]
  issue-url: https://github.com/data4decisionmakers/data4decisionmakers.github.io/issues
  cookie-consent:
    type: express
    style: simple
    palette: light
  google-analytics:
    tracking-id: G-N5RC41JEQ8
    anonymize-ip: true

format:
  html:
    theme: [pulse, custom.scss]
    css: style.css
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 250px
      gutter-width: 1.5rem
    toc: false